[project]
name = "landing-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agentic-doc>=0.2.3",
    "streamlit>=1.45.1",
    "streamlit-pdf-viewer>=0.0.23",
]
